# Dependency Review Configuration
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review

# Vulnerability check configuration
vulnerability-check: true
fail-on-severity: 'moderate'

# License check configuration  
license-check: true
allowed-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD
  - Unlicense

denied-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-1.0
  - AGPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0
  - CDDL-1.0
  - CDDL-1.1
  - EPL-1.0
  - EPL-2.0
  - EUPL-1.1
  - EUPL-1.2

# Additional configuration
retry-on-snapshot-warnings: true
warn-only: false
comment-summary-in-pr: 'always'

# External dependencies configuration
allow-ghsas: []
allow-dependencies-licenses: []