// SPDX-License-Identifier: MIT
// Copyright (c) 2025 the99studio
/**
 * Configuration schema definitions for Project Fusion
 */
import { z } from 'zod';

/**
 * File extension groups with support for custom categories
 */
const ParsedFileExtensionsSchema = z.object({
    backend: z.array(z.string()).default([".cs", ".go", ".java", ".php", ".py", ".rb", ".rs"]),
    config: z.array(z.string()).default([".json", ".toml", ".xml", ".yaml", ".yml"]),
    cpp: z.array(z.string()).default([".c", ".cc", ".cpp", ".h", ".hpp"]),
    doc: z.array(z.string()).default([".adoc", ".md", ".rst"]),
    godot: z.array(z.string()).default([".cfg", ".cs", ".gd", ".import", ".tscn", ".tres"]),
    scripts: z.array(z.string()).default([".bat", ".cmd", ".ps1", ".sh"]),
    web: z.array(z.string()).default([".css", ".html", ".js", ".jsx", ".svelte", ".ts", ".tsx", ".vue"]),
}).and(z.record(z.string(), z.array(z.string())));

/**
 * Complete configuration schema for version 1
 */
export const ConfigSchemaV1 = z.object({
    allowSymlinks: z.boolean().default(false),
    copyToClipboard: z.boolean().default(false),
    generatedFileName: z.string().default("project-fusioned"),
    generateHtml: z.boolean().default(true),
    generateMarkdown: z.boolean().default(true),
    generateText: z.boolean().default(true),
    maxFileSizeKB: z.number().default(1024),
    maxFiles: z.number().min(1).default(10000),
    maxTotalSizeMB: z.number().min(0.001).default(100),
    parseSubDirectories: z.boolean().default(true),
    parsedFileExtensions: ParsedFileExtensionsSchema.default({
        backend: [".cs", ".go", ".java", ".php", ".py", ".rb", ".rs"],
        config: [".json", ".toml", ".xml", ".yaml", ".yml"],
        cpp: [".c", ".cc", ".cpp", ".h", ".hpp"],
        doc: [".adoc", ".md", ".rst"],
        godot: [".cfg", ".cs", ".gd", ".import", ".tscn", ".tres"],
        scripts: [".bat", ".cmd", ".ps1", ".sh"],
        web: [".css", ".html", ".js", ".jsx", ".svelte", ".ts", ".tsx", ".vue"]
    }),
    ignorePatterns: z.array(z.string()).default([
        "project-fusion.json",
        "project-fusion.log",
        "project-fusioned.*",
        "node_modules/",
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "dist/",
        "build/",
        "*.min.js",
        "*.min.css",
        ".env",
        ".env.*",
        "*.key",
        "*.pem",
        "**/credentials/*",
        "**/secrets/*",
        "*.log",
        "logs/",
        ".DS_Store",
        "Thumbs.db",
        ".vscode/",
        ".idea/",
        "*.swp",
        "*.swo",
        "*.zip",
        "*.tar",
        "*.tgz",
        "*.gz",
        "*.7z",
        "*.rar",
        "*.png",
        "*.jpg",
        "*.jpeg",
        "*.gif",
        "*.bmp",
        "*.ico",
        "*.svg",
        "*.webp",
        "*.pdf",
        "*.doc",
        "*.docx",
        "*.xls",
        "*.xlsx",
        "*.ppt",
        "*.pptx",
        "*.mp3",
        "*.mp4",
        "*.avi",
        "*.mov",
        "*.wmv",
        "*.flv",
        "*.wav",
        "*.flac",
        "*.unitypackage",
        "*.uasset",
        "*.fbx",
        "*.obj",
        "*.blend",
        "*.exe",
        "*.dll",
        "*.so",
        "*.dylib",
        "*.a",
        "*.o",
        "*.pyc",
        "*.pyo",
        "*.class",
        "*.jar",
        "*.war"
    ]),
    rootDirectory: z.string().default("."),
    schemaVersion: z.literal(1).default(1),
    useGitIgnoreForExcludes: z.boolean().default(true),
});