name: CI

on:
  push:
    branches: 
      - '**'
      - '!skip-ci/**'
      - '!no-ci/**'
      - '!wip/**'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    uses: ./.github/workflows/build-test.yml